# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-WXZF9_OufQ36x5-Jx91cQ_SixSP2CQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
covid=pd.read_csv("covid_19.csv")
print(covid)

covid.head

display(covid.drop_duplicates())

x=covid.drop("deaths",axis=1)
y=covid['deaths']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=0)
x_train

y_test

x_test



plt.plot(covid.cases,covid.deaths)


plt.xlabel('covid.cases')
# naming the y axis
plt.ylabel('covid.deaths')

# giving a title to my graph
plt.title('My first graph!')

# function to show the plot
plt.show()